import type { CaseState } from "./constants";

export const allowedTransitions: Readonly<Record<CaseState, readonly CaseState[]>> = {
  RECEIVED: ["EXTRACTING_CLAIMS", "CLOSED_UNRESOLVED"],
  EXTRACTING_CLAIMS: ["CLAIMS_READY", "VERIFICATION_FAILED_RETRYABLE", "CLOSED_UNRESOLVED"],
  CLAIMS_READY: ["ACQUIRING_EVIDENCE", "VERIFICATION_FAILED_RETRYABLE", "CLOSED_UNRESOLVED"],
  ACQUIRING_EVIDENCE: ["EVALUATING", "VERIFICATION_FAILED_RETRYABLE", "CLOSED_UNRESOLVED"],
  EVALUATING: [
    "ACTIONABLE",
    "NEEDS_IDENTIFIER",
    "BLOCKED_CONFLICT",
    "NO_AUTHORITATIVE_EVIDENCE",
    "VERIFICATION_FAILED_RETRYABLE",
    "CLOSED_UNRESOLVED",
  ],
  ACTIONABLE: ["AWAITING_APPROVAL", "ACQUIRING_EVIDENCE", "CLOSED_UNRESOLVED"],
  NEEDS_IDENTIFIER: ["EXTRACTING_CLAIMS", "ACQUIRING_EVIDENCE", "CLOSED_UNRESOLVED"],
  BLOCKED_CONFLICT: ["ACQUIRING_EVIDENCE", "CLOSED_UNRESOLVED"],
  NO_AUTHORITATIVE_EVIDENCE: ["ACQUIRING_EVIDENCE", "CLOSED_UNRESOLVED"],
  VERIFICATION_FAILED_RETRYABLE: ["EXTRACTING_CLAIMS", "ACQUIRING_EVIDENCE", "CLOSED_UNRESOLVED"],
  AWAITING_APPROVAL: [
    "ACTIONABLE",
    "CONTACTING_VERIFIED_CHANNEL",
    "ACQUIRING_EVIDENCE",
    "CLOSED_UNRESOLVED",
  ],
  CONTACTING_VERIFIED_CHANNEL: ["AWAITING_REPLY", "VERIFICATION_FAILED_RETRYABLE"],
  AWAITING_REPLY: ["REMEDY_CONFIRMED", "VERIFICATION_FAILED_RETRYABLE", "CLOSED_UNRESOLVED"],
  REMEDY_CONFIRMED: ["RESOLVED", "CLOSED_UNRESOLVED"],
  RESOLVED: [],
  CLOSED_UNRESOLVED: [],
};

export class InvalidCaseTransitionError extends Error {
  readonly code = "INVALID_CASE_TRANSITION";

  constructor(
    readonly from: CaseState,
    readonly to: CaseState,
  ) {
    super(`Case cannot transition from ${from} to ${to}`);
    this.name = "InvalidCaseTransitionError";
  }
}

export function assertTransition(from: CaseState, to: CaseState): void {
  if (!allowedTransitions[from].includes(to)) {
    throw new InvalidCaseTransitionError(from, to);
  }
}
